# Тип базы данных: H2 или MYSQL
storage:
  type: H2
  # MySQL настройки, если "type" стоит "MYSQL"
  mysql:
    host: "localhost"
    port: 3306
    database: "npromo"
    username: "root"
    password: ""

# Режим промокода: UNLIMITED или MEDIA
# UNLIMITED: Игроки могут активировать любое количество кодов, но каждый код только один раз.
# MEDIA: Игроки могут активировать только один код, один раз.
mode: UNLIMITED

# Настройки режима "MEDIA"
media-settings:
  # Проверяет айпи, если этот айпи активировал то не дает активировать.
  check-ip: true
